// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBK18bn9Bq3e2SQNwfMMgtXA_PF8hRpvNU',
    appId: '1:316491830875:web:1d682c6f646fd5f345117e',
    messagingSenderId: '316491830875',
    projectId: 'quizland-ba92d',
    authDomain: 'quizland-ba92d.firebaseapp.com',
    storageBucket: 'quizland-ba92d.firebasestorage.app',
    measurementId: 'G-WG6SPZL2EV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtjmMXBu9ZLuKmrAhOBvwt9kheFwm5xSw',
    appId: '1:316491830875:android:a06fad2ded4a2e8245117e',
    messagingSenderId: '316491830875',
    projectId: 'quizland-ba92d',
    storageBucket: 'quizland-ba92d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPQqS4F0SfySKiu_pClWa2cXBMXgGIE7w',
    appId: '1:316491830875:ios:a91cc68684b0a4a045117e',
    messagingSenderId: '316491830875',
    projectId: 'quizland-ba92d',
    storageBucket: 'quizland-ba92d.firebasestorage.app',
    iosBundleId: 'com.chamie.quizlandApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAPQqS4F0SfySKiu_pClWa2cXBMXgGIE7w',
    appId: '1:316491830875:ios:a91cc68684b0a4a045117e',
    messagingSenderId: '316491830875',
    projectId: 'quizland-ba92d',
    storageBucket: 'quizland-ba92d.firebasestorage.app',
    iosBundleId: 'com.chamie.quizlandApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBK18bn9Bq3e2SQNwfMMgtXA_PF8hRpvNU',
    appId: '1:316491830875:web:ce3d01a2caee642845117e',
    messagingSenderId: '316491830875',
    projectId: 'quizland-ba92d',
    authDomain: 'quizland-ba92d.firebaseapp.com',
    storageBucket: 'quizland-ba92d.firebasestorage.app',
    measurementId: 'G-CFWN84KYKL',
  );
}
