Map<int, List<String>> matchingLevel = {
  2: [
    'one.jpg',
    'two.jpg',
    'three.jpg',
    'four.jpg',
    'five.jpg',
    'six.jpg',
    'seven.jpg',
    'eight.jpg',
    'nine.jpg',
    'ten.jpg',
    'my.png',
    'name.jpg',
    'old.png',
    'what.png',
    'your.png'
  ],
  1: [
    'bye.jpg',
    'fine.jpg',
    'hello.jpg',
    'how.png',
    'I.jpg',
    'thank you.png',
    'you.jpg',
  ],
  3: [
    'friend.jpg',
    'Mr.jpg',
    'Ms.jpg',
    'no.jpg',
    'teacher.jpg',
    'that.jpg',
    'this.jpg',
    'yes.jpg'
  ],
  4: [
    'ear.jpg',
    'eye.jpg',
    'face.jpg',
    'hair.jpg',
    'hand.jpg',
    'mouth.jpg',
    'nose.jpg',
    'open.jpg',
    'touch.jpg',
  ],
  5: [
    'cook.jpg',
    'dance.jpg',
    'draw.jpg',
    'paint.jpg',
    'run.jpg',
    'sing.jpg',
    'swim.jpg',
    'walk.jpg'
  ],
  6: [
    'art room.jpg',
    'classroom.jpg',
    'computer room.jpg',
    'library.jpg',
    'music room.jpg',
    'playground.jpg',
    'school.jpg',
  ],
  7: [
    'close.jpg',
    'come in.jpg',
    'go out.jpg',
    'sit down.jpg',
    'speak.jpg',
    'stand up.jpg',
  ],
  8: [
    'book.jpg',
    'eraser.jpg',
    'notebook.jpg',
    'pen.jpg',
    'pencil case.jpg',
    'ruler.jpg',
    'school bag.jpg',
  ],
  9: [
    'black.jpg',
    'blue.jpg',
    'brown.jpg',
    'colour.png',
    'green.jpg',
    'orange.jpg',
    'red.jpg',
    'white.jpg',
    'yellow.jpg'
  ],
  10: [
    'badminton.jpg',
    'basketball.jpg',
    'break time.jpg',
    'chat.jpg',
    'chess.jpg',
    'football.jpg',
    'play.jpg',
    'table tennis.jpg',
    'volleyball.jpg',
    'word puzzle.jpg',
  ],
  11: [
    '11.jpg',
    '12.jpg',
    '13.jpg',
    '14.jpg',
    '15.jpg',
    '16.jpg',
    '17.jpg',
    '18.jpg',
    '19.jpg',
    '20.jpg',
    'brother.jpg',
    'father.jpg',
    'mother.jpg',
    'sister.jpg',
    'sure.jpg',
  ],
  12: [
    'cook.png',
    'doctor.jpg',
    'driver.jpg',
    'farmer.jpg',
    'job.jpg',
    'nurse.jpg',
    'singer.jpg',
    'teacher.jpg',
    'worker.jpg',
  ],
  13: [
    'bathroom.jpg',
    'bedroom.jpg',
    'big.jpg',
    'chair.jpg',
    'here.jpg',
    'house.jpg',
    'in.jpg',
    'kitchen.jpg',
    'lamp.jpg',
    'living room.jpg',
    'on.jpg',
    'room.jpg',
    'table.jpg',
    'teddy bear.jpg',
    'there.jpg'
  ],
  14: [
    'bed.jpg',
    'desk.jpg',
    'door.jpg',
    'new.jpg',
    'old.jpg',
    'small.jpg',
    'window.jpg',
  ],
  15: [
    'bean.jpg',
    'bread.jpg',
    'chicken.jpg',
    'dinning table.jpg',
    'egg.jpg',
    'fish.jpg',
    'juice.jpg',
    'meat.jpg',
    'milk.jpg',
    'rice.jpg',
    'water.jpg',
  ],
  16: [
    'bird.jpg',
    'cat.jpeg',
    'dog.jpeg',
    'goldfish.jpeg',
    'many.jpg',
    'parrot.jpg',
    'pet.png',
    'rabbit.jpeg',
    'some.jpg',
  ],
  17: [
    'bus.jpeg',
    'car.jpeg',
    'count.jpeg',
    'kite.jpeg',
    'plane.jpeg',
    'ship.jpeg',
    'teddy bear.jpeg',
    'toy.jpeg',
    'train.jpeg',
    'truck.jpeg',
  ],
  18: [
    'draw a picture.jpeg',
    'fun.jpg',
    'listen to music.jpeg',
    'play basketball.jpg',
    'read.jpeg',
    'sing.jpeg',
    'watch TV.jpeg',
    'write.jpeg'
  ],
  19: [
    'cycle.jpeg',
    'fly a kite.jpeg',
    'outdoor activities.jpeg',
    'park.jpeg',
    'run.jpeg',
    'skate.jpeg',
    'skip.jpeg',
    'sport.jpeg',
  ],
  20: [
    'climb.jpeg',
    'count.jpg',
    'elephant.jpeg',
    'horse.jpeg',
    'monkey.jpeg',
    'peacock.jpeg',
    'swing.jpeg',
    'tiger.jpeg'
  ]
};
