Map<int, List<String>> matchingLevel = {
  2: [
    'one.jpg',
    'two.jpg',
    'three.jpg',
    'four.jpg',
    'five.jpg',
    'six.jpg',
    'seven.jpg',
    'eight.jpg',
    'nine.jpg',
    'ten.jpg',
    'my.png',
    'name.jpg',
    'old.png',
    'what.png',
    'your.png'
  ],
  1: [
    'bye.jpg',
    'fine.jpg',
    'hello.jpg',
    'how.png',
    'I.jpg',
    'thank you.png',
    'you.jpg',
  ],
  3: [
    'friend.jpg',
    'Mr.jpg',
    'Ms.jpg',
    'no.jpg',
    'teacher.jpg',
    'that.jpg',
    'this.jpg',
    'yes.jpg'
  ],
  4: [
    'ear.jpg',
    'eye.jpg',
    'face.jpg',
    'hair.jpg',
    'hand.jpg',
    'mouth.jpg',
    'nose.jpg',
    'open.jpg',
    'touch.jpg',
  ],
  5: [
    'cook.jpg',
    'dance.jpg',
    'draw.jpg',
    'paint.jpg',
    'run.jpg',
    'sing.jpg',
    'swim.jpg',
    'walk.jpg'
  ],
  6: [
    'art room.jpg',
    'classroom.jpg',
    'computer room.jpg',
    'library.jpg',
    'music room.jpg',
    'playground.jpg',
    'school.jpg',
  ],
  7: [
    'close.jpg',
    'come in.jpg',
    'go out.jpg',
    'sit down.jpg',
    'speak.jpg',
    'stand up.jpg',
  ],
  8: [
    'book.jpg',
    'eraser.jpg',
    'notebook.jpg',
    'pen.jpg',
    'pencil case.jpg',
    'ruler.jpg',
    'school bag.jpg',
  ],
  9: [
    'black.jpg',
    'blue.jpg',
    'brown.jpg',
    'colour.png',
    'green.jpg',
    'orange.jpg',
    'red.jpg',
    'white.jpg',
    'yellow.jpg'
  ],
  10: [
    'badminton.jpg',
    'basketball.jpg',
    'break time.jpg',
    'chat.jpg',
    'chess.jpg',
    'football.jpg',
    'play.jpg',
    'table tennis.jpg',
    'volleyball.jpg',
    'word puzzle.jpg',
  ],
};
